org.gradle.jvmargs=-Xmx2G

archives_base_name=caramelChat
mod_version=1.2.3-SNAPSHOT
maven_group=moe.caramel

minecraft_version=26.2
fabric_loader_version=0.19.3
forge_version=26.2-65.1.0
neoforge_version=26.2.0.76

# Minotaur
release_channel=release
support_versions=26.2

# Other mods
xaeros_minimap_version=fabric-26.2-26.4.2
