# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 3.
loaderVersion="[3,)" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GNU LGPL 3.0"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/LemonCaramel/caramelChat/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="caramelchat" #mandatory

# The version number of the mod
version="${version}" #mandatory

# A display name for the mod
displayName="caramelChat" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
updateJSONURL="https://api.modrinth.com/updates/caramel-chat/forge_updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://caramel.moe/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png" #optional

# A text field displayed in the mod UI
#credits="" #optional

# A text field displayed in the mod UI
authors="LemonCaramel, Axeryok (Native Library)" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Provides an enhanced IME input experience in Minecraft.
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="caramelchat.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency
[[dependencies.caramelchat]]
    modId="neoforge"
    type="required"
    versionRange="[20.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.caramelchat]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5,)"
    ordering="NONE"
    side="CLIENT"
