name: Build caramelChat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: caramelChat-artifacts
          path: |
            fabric/build/libs/**.jar
            forge/build/libs/**.jar
            neoforge/build/libs/**.jar
