name: Build caramelChat

on:
  push:
    branches: [ dev/1.19.4 ]
  pull_request:
    branches: [ dev/1.19.4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup git config
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Action"

      - name: Build with Gradle
        run: |
          ./gradlew build --stacktrace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: caramelChat-artifacts
          path: |
            fabric/build/libs/**.jar
            forge/build/libs/**.jar
